# Generated by Django 2.2.5 on 2019-10-10 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Comunidad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Comunidad'),
        ),
    ]
